### ISSUE TITLE
Job mode opens

### ISSUE THREAD

**Issue by ghost** [jaflesch/tinder-autolike#25]
Hi, when script starts like, job mode opens and stay staticaly.

function hasBlacklistKeywords(bio) {
	const blacklist = [
		'ladyboy',
		'banci',
		'bencong',
		'lady boy',
		'not a lady',
		'not lady',
		'not a girl',
		'not girl',
		'trans',
		'shemale',
		'chubby',
		//' lb ',
	];

	for (item of blacklist) {
		if (bio.toLowerCase().indexOf(item) !== -1) {
			console.log('skipping profile, matched blacklist keyword ' + item);
			return true;
		}
	}

	return false;
}

function hasValidProfile() {
	try {
		const bioContainer = document.querySelector('.profileCard .profileContent .profileCard__card .BreakWord');
		if (!bioContainer) return true;
		const bio = bioContainer.textContent;
		console.log(bio);
		return !hasBlacklistKeywords(bio);
	} catch (e) {
		// console.log(e);
		return true; // possible empty bio
	}
}

function checkTinder() {
	const base = "https://tinder.com/";
	return window.location.href.startsWith(base + "app/recs") || window.location.href.startsWith(base + "app/matches");
}

function isMatch() {
	return document.querySelector('a.active');
}

// prevent async execution
function pause(milliseconds) {
	const dt = new Date();
	while ((new Date()) - dt <= milliseconds) { /* Do nothing */ }
}

function trickTinder() {
	const infoClassName = 'focus-button-style';
	const nbButtons = document.getElementsByClassName("button").length;
	const buttons = document.getElementsByClassName("button")

	const dislike = nbButtons === 5 ? buttons[1] : buttons[0];
	const like = nbButtons === 5 ? buttons[3] : buttons[2];

	// Open profile bio
	const info = document.getElementsByClassName(infoClassName)[0];
	if (info) {
		info.click();
	}
	pause(600);

	// Like or deslike depending on validation
	if (hasValidProfile()) {
		like.click();

		const thereIsMatch = isMatch();
		if (thereIsMatch) {
			console.log('------------- IT\'S A MATCH ! -------------');
			thereIsMatch.click();
		}
	} else {
		dislike.click();
	}

	// If reached max likes per day then show modal and get it's content...
	// Check if there is any subscription button...
	if (document.getElementsByClassName('productButton__subscriptionButton').length > 0) {
		// We get the counter thing
		const hms = document.getElementsByClassName('Fz($ml)')[0].textContent;
		// Split it at the colons
		const a = hms.split(':');
		// Minutes are worth 60 seconds. Hours are worth 60 minutes. 1 second = 1kmilliseconds.
		// Genius... rocket science...
		const seconds = (+a[0]) * 60 * 60 + (+a[1]) * 60 + (+a[2])

		return seconds * 1000;
	}
}

function checkOkCupid() {
	return window.location.href.startsWith("https://www.okcupid.com/doubletake");
}
function trickOkCupid() {
	// Press the like button
	document.getElementsByClassName('cardactions-action--like')[0].click();
}

// There is a lot more fun that can be achieved
// Need to add socket puppetry (VPNs solutions? several accounts?) - :D
// TODO: Need to accept automatically permissions except for
// TODO: Need to add ANN for fake pics
// TODO: Need to add RNN for fake messages

function getRandomPeriod() {
	return Math.round(Math.random() * (2000 - 500)) + 500;
}

(function loopSasori() {
	// A random period between 500ms and 2secs
	let randomPeriod = getRandomPeriod();

	setTimeout(function () {
		randomPeriod = undefined;

		if (checkTinder()) {
			const delay = trickTinder();

			if (delay) {
				console.log('Too many likes for now, have to wait: ' + delay + ' ms');
				randomPeriod = delay;
			}
		} else if (checkOkCupid()) {
			trickOkCupid();
		}

		if (!randomPeriod) {
			loopSasori();
		} else {
			setTimeout(loopSasori, randomPeriod);
		}
	}, randomPeriod);
}());

**Comment by danielrichter78** [comment]
no fix yet?

**Comment by edoardo-bt** [comment]
same problem here

**Comment by edoardo-bt** [comment]
As a guy pointed out in another request, the bottoms have changed, here's a working version

**Comment by edoardo-bt** [comment]
function hasBlacklistKeywords(bio) {
	const blacklist = [
		'ladyboy',
		'banci',
		'bencong',
		'lady boy',
		'not a lady',
		'not lady',
		'not a girl',
		'not girl',
		'trans',
		'shemale',
		'chubby',
		//' lb ',
	];

	for (item of blacklist) {
		if (bio.toLowerCase().indexOf(item) !== -1) {
			console.log('skipping profile, matched blacklist keyword ' + item);
			return true;
		}
	}

	return false;
}

function hasValidProfile() {
	try {
		const bioContainer = document.querySelector('.profileCard .profileContent .profileCard__card .BreakWord');
		if (!bioContainer) return true;
		const bio = bioContainer.textContent;
		console.log(bio);
		return !hasBlacklistKeywords(bio);
	} catch (e) {
		// console.log(e);
		return true; // possible empty bio
	}
}

function checkTinder() {
	const base = "https://tinder.com/";
	return window.location.href.startsWith(base + "app/recs") || window.location.href.startsWith(base + "app/matches");
}

function isMatch() {
	return document.querySelector('a.active');
}

// prevent async execution
function pause(milliseconds) {
	const dt = new Date();
	while ((new Date()) - dt <= milliseconds) { /* Do nothing */ }
}

function trickTinder() {
	var infoClassName = 'recCard__info';
	var dislike = document.getElementsByClassName("recsGamepad__button")[0];
	var like = document.getElementsByClassName("recsGamepad__button")[2];
	var like = document.getElementsByClassName("button Lts($ls-s) Z(0) CenterAlign Mx(a) Cur(p) Tt(u) Bdrs(50%) P(0) Fw($semibold) focus-button-style Bxsh($bxsh-btn) Expand D(b) Bgc(#fff) Trstf(e) Trsdu($normal) Wc($transform) Pe(a) Scale(1.1):h Scale(.9):a")[2];

	// Open profile bio
	const info = document.getElementsByClassName(infoClassName)[0];
	if (info) {
		info.click();
	}
	pause(600);

	// Like or deslike depending on validation
	if (hasValidProfile()) {
		like.click();

		const thereIsMatch = isMatch();
		if (thereIsMatch) {
			console.log('------------- IT\'S A MATCH ! -------------');
			thereIsMatch.click();
		}
	} else {
		dislike.click();
	}

	// If reached max likes per day then show modal and get it's content...
	// Check if there is any subscription button...
	if (document.getElementsByClassName('productButton__subscriptionButton').length > 0) {
		// We get the counter thing
		const hms = document.getElementsByClassName('Fz($ml)')[0].textContent;
		// Split it at the colons
		const a = hms.split(':');
		// Minutes are worth 60 seconds. Hours are worth 60 minutes. 1 second = 1kmilliseconds.
		// Genius... rocket science...
		const seconds = (+a[0]) * 60 * 60 + (+a[1]) * 60 + (+a[2])

		return seconds * 1000;
	}
}

function checkOkCupid() {
	return window.location.href.startsWith("https://www.okcupid.com/doubletake");
}
function trickOkCupid() {
	// Press the like button
	document.getElementsByClassName('cardactions-action--like')[0].click();
}

// There is a lot more fun that can be achieved
// Need to add socket puppetry (VPNs solutions? several accounts?) - :D
// TODO: Need to accept automatically permissions except for
// TODO: Need to add ANN for fake pics
// TODO: Need to add RNN for fake messages

function getRandomPeriod() {
	return Math.round(Math.random() * (3500 - 1500)) + 500;
}

(function loopSasori() {
	// A random period between 4sec and 2 sec
	let randomPeriod = getRandomPeriod();

	setTimeout(function () {
		randomPeriod = undefined;

		if (checkTinder()) {
			const delay = trickTinder();

			if (delay) {
				console.log('Too many likes for now, have to wait: ' + delay + ' ms');
				randomPeriod = delay;
			}
		} else if (checkOkCupid()) {
			trickOkCupid();
		}

		if (!randomPeriod) {
			loopSasori();
		} else {
			setTimeout(loopSasori, randomPeriod);
		}
	}, randomPeriod);
}());

**Comment by ghost** [comment]
Hi everyone,

just change the number 0 for 1 in the line : 	**const info = document.getElementsByClassName(infoClassName)[1];**

Follow the work script:

function hasBlacklistKeywords(bio) {
	const blacklist = [
		'ladyboy',
		'banci',
		'bencong',
		'lady boy',
		'not a lady',
		'not lady',
		'not a girl',
		'not girl',
		'trans',
		'shemale',
		'chubby',
		//' lb ',
	];

	for (item of blacklist) {
		if (bio.toLowerCase().indexOf(item) !== -1) {
			console.log('skipping profile, matched blacklist keyword ' + item);
			return true;
		}
	}

	return false;
}

function hasValidProfile() {
	try {
		const bioContainer = document.querySelector('.profileCard .profileContent .profileCard__card .BreakWord');
		if (!bioContainer) return true;
		const bio = bioContainer.textContent;
		console.log(bio);
		return !hasBlacklistKeywords(bio);
	} catch (e) {
		// console.log(e);
		return true; // possible empty bio
	}
}

function checkTinder() {
	const base = "https://tinder.com/";
	return window.location.href.startsWith(base + "app/recs") || window.location.href.startsWith(base + "app/matches");
}

function isMatch() {
	return document.querySelector('a.active');
}

// prevent async execution
function pause(milliseconds) {
	const dt = new Date();
	while ((new Date()) - dt <= milliseconds) { /* Do nothing */ }
}

function trickTinder() {
	const infoClassName = 'focus-button-style';
	const nbButtons = document.getElementsByClassName("button").length;
	const buttons = document.getElementsByClassName("button")

	const dislike = nbButtons === 5 ? buttons[1] : buttons[0];
	const like = nbButtons === 5 ? buttons[3] : buttons[2];

	// Open profile bio
	**const info = document.getElementsByClassName(infoClassName)[1];**
	if (info) {
		info.click();
	}
	pause(600);

	// Like or deslike depending on validation
	if (hasValidProfile()) {
		like.click();

		const thereIsMatch = isMatch();
		if (thereIsMatch) {
			console.log('------------- IT\'S A MATCH ! -------------');
			thereIsMatch.click();
		}
	} else {
		dislike.click();
	}

	// If reached max likes per day then show modal and get it's content...
	// Check if there is any subscription button...
	if (document.getElementsByClassName('productButton__subscriptionButton').length > 0) {
		// We get the counter thing
		const hms = document.getElementsByClassName('Fz($ml)')[0].textContent;
		// Split it at the colons
		const a = hms.split(':');
		// Minutes are worth 60 seconds. Hours are worth 60 minutes. 1 second = 1kmilliseconds.
		// Genius... rocket science...
		const seconds = (+a[0]) * 60 * 60 + (+a[1]) * 60 + (+a[2])

		return seconds * 1000;
	}
}

function checkOkCupid() {
	return window.location.href.startsWith("https://www.okcupid.com/doubletake");
}
function trickOkCupid() {
	// Press the like button
	document.getElementsByClassName('cardactions-action--like')[0].click();
}

// There is a lot more fun that can be achieved
// Need to add socket puppetry (VPNs solutions? several accounts?) - :D
// TODO: Need to accept automatically permissions except for
// TODO: Need to add ANN for fake pics
// TODO: Need to add RNN for fake messages

function getRandomPeriod() {
	return Math.round(Math.random() * (2000 - 500)) + 500;
}

(function loopSasori() {
	// A random period between 500ms and 2secs
	let randomPeriod = getRandomPeriod();

	setTimeout(function () {
		randomPeriod = undefined;

		if (checkTinder()) {
			const delay = trickTinder();

			if (delay) {
				console.log('Too many likes for now, have to wait: ' + delay + ' ms');
				randomPeriod = delay;
			}
		} else if (checkOkCupid()) {
			trickOkCupid();
		}

		if (!randomPeriod) {
			loopSasori();
		} else {
			setTimeout(loopSasori, randomPeriod);
		}
	}, randomPeriod);
}());

**Comment by edoardo-bt** [comment]
Hi man, thanks for working on that, but if I run it, it swipes right once and then wants to "report the profile" for the next ones. So I guess it doesn't work. If you want to have a look at what I've posted, like button works, but it doesn't check the profile bio and also the "do not like button" doesn't work

**Comment by ashleycolton** [comment]
Hi i changed "const info" from 0 to 1, when i type into MSedge console it says undefined. where have I used it wrong?
the code is here

function hasBlacklistKeywords(bio) {
	const blacklist = [
		'ladyboy',
		'banci',
		'bencong',
		'lady boy',
		'not a lady',
		'not lady',
		'not a girl',
		'not girl',
		'trans',
		'shemale',
		'chubby',
		//' lb ',
	];

	for (item of blacklist) {
		if (bio.toLowerCase().indexOf(item) !== -1) {
			console.log('skipping profile, matched blacklist keyword ' + item);
			return true;
		}
	}

	return false;
}

function hasValidProfile() {
	try {
		const bioContainer = document.querySelector('.profileCard .profileContent .profileCard__card .BreakWord');
		if (!bioContainer) return true;
		const bio = bioContainer.textContent;
		console.log(bio);
		return !hasBlacklistKeywords(bio);
	} catch (e) {
		// console.log(e);
		return true; // possible empty bio
	}
}

function checkTinder() {
	const base = "https://tinder.com/";
	return window.location.href.startsWith(base + "app/recs") || window.location.href.startsWith(base + "app/matches");
}

function isMatch() {
	return document.querySelector('a.active');
}

// prevent async execution
function pause(milliseconds) {
	const dt = new Date();
	while ((new Date()) - dt <= milliseconds) { /* Do nothing */ }
}

function trickTinder() {
	const infoClassName = 'focus-button-style';
	const nbButtons = document.getElementsByClassName("button").length;
	const buttons = document.getElementsByClassName("button")

	const dislike = nbButtons === 5 ? buttons[1] : buttons[0];
	const like = nbButtons === 5 ? buttons[3] : buttons[2];

	// Open profile bio
	const info = document.getElementsByClassName(infoClassName)[1];
	if (info) {
		info.click();
	}
	pause(600);

	// Like or deslike depending on validation
	if (hasValidProfile()) {
		like.click();

		const thereIsMatch = isMatch();
		if (thereIsMatch) {
			console.log('------------- IT\'S A MATCH ! -------------');
			thereIsMatch.click();
		}
	} else {
		dislike.click();
	}

	// If reached max likes per day then show modal and get it's content...
	// Check if there is any subscription button...
	if (document.getElementsByClassName('productButton__subscriptionButton').length > 0) {
		// We get the counter thing
		const hms = document.getElementsByClassName('Fz($ml)')[0].textContent;
		// Split it at the colons
		const a = hms.split(':');
		// Minutes are worth 60 seconds. Hours are worth 60 minutes. 1 second = 1kmilliseconds.
		// Genius... rocket science...
		const seconds = (+a[0]) * 60 * 60 + (+a[1]) * 60 + (+a[2])

		return seconds * 1000;
	}
}
