### ISSUE TITLE
Not working need to update

### ISSUE THREAD

**Issue by niixllk** [jaflesch/tinder-autolike#3]
Tinder script is not working.

**Comment by avasn** [comment]
you can fix it without changing the script its self by changing the value in tinder's website from recsGamepad__button D to  recsGamepad__button--like and the script will work

**Comment by niixllk** [comment]
Yeah, it worked. Sorry, I am a noob. I tried to do the same with replacing button class on Bumble. It is working there. https://pastebin.com/gBFNfKkU can u add this in your script?

**Comment by jaflesch** [comment]
Sorry the delay. Script is now fixed (updated element selector)!
