### ISSUE TITLE
An option for auto-dislike

### ISSUE THREAD

**Issue by pedrohrcunha** [jaflesch/tinder-autolike#7]
Hello, 

first of all I would like to thank you for your script. I'm having great fun here in Brazil! Really thanks. 

So, since the shadow rules of Tinder bans or lower you to the bottom of the deck, I was wondering if you could help me out writing a dislike option in your script. As far as I know, an average of 3 dislikes for 7 likes is way better than an entirely autolike script, you see?

**Comment by jaflesch** [comment]
Hi, Pedro,

No problem. In a few days i'll add this new functionality. Thanks for your suggestion! 

Glad to hear the script is also giving fun moments to you. haha

**Comment by pedrohrcunha** [comment]
@jaflesch thanks for your kind reply! As a matter of fact, if you're interested in the implicit rules of Tinder, take a look on these articles: https://www.swipehelper.com/2016/11/16/tinder-algorithm/

https://www.swipehelper.com/2019/03/24/tinder-changes-elo-ranking-algorithm-new-score-system-just-same/https://www.swipehelper.com/2019/03/24/tinder-changes-elo-ranking-algorithm-new-score-system-just-same/

I've been extracting data to test the limits of the algorithm. I have this plan to turn this into an odd work of art. I will credit you, apropriately.

**Comment by pedrohrcunha** [comment]
@jaflesch dude, we're both brazilians. Can I add you on a social media? No need to link it here, I can find you.

**Comment by Lusitaniae** [comment]
My PR #9 also helps here by using a blacklist to determine when to swipe left.
